name: Release Go structs

"on":
  workflow_dispatch:
    inputs:
      ygot_version:
        description: "Ygot version (vX.Y.Z)."
        required: true
        type: string
        default: v0.24.4
      srlinux_version:
        description: "SR Linux release (vYY.M.A)"
        required: true
        type: string
      release_suffix:
        description: "Package release suffix that appends to the SR Linux version. E.g. 22.11.1-rc1. Defaults to rc1"
        required: false
        type: string
        default: "rc1"
env:
  GOVER: 1.18.4

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVER }}

      - name: Set env vars
        run: |
          echo "YGOT_VERSION=${{ inputs.ygot_version }}" >> $GITHUB_ENV
          echo "SRLINUX_VERSION=${{ inputs.srlinux_version }}" >> $GITHUB_ENV
          echo "RELEASE_SUFFIX=${{ inputs.release_suffix }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      # add `actions`` git user credentials
      - uses: fregante/setup-git-user@v1

      - name: Publish structs
        run: make release
